# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -c Release 
    - name: Test
      run: dotnet test --no-build -c Release --verbosity normal
    - name: Create ZIP of Build Output
      run: |
        mkdir -p ./artifacts
        zip -r ./artifacts/build_output.zip ./GildedRose/bin/Release/net8.0
    - name: Upload Build ZIP Artifact
      uses: actions/upload-artifact@v3
      with:
        name: build-output
        path: ./artifacts/build_output.zip

